/*
in a company an employee is paid under
	-if his basic salary is less than 5000
		than HRA = 20% of his basic salary
		and Da  = 50 % of his basic salary
	-if his salary is either equal to or above 50000
		than HRA = 2000
		and Da = 75% of his basic salary
	-if the employee salary is given by the user
		than write a program to calculate his gross salary
that is gross salary is basic salay + HRA + DA
*/

/*
Write a program to calculate electricity bill accoding to the following charges.
	0-100 than 2 Rs per unit
	101-350 than 3 Rs per unit
	151 and above 7 Rs per unit
 also add 200 rs fixed meter charges
*/

/*
Write a program which accepts days as a intger
	Ex = 700 or 200 days
and display total number of years months and week in it
	like 3 year 2 month 1 week 1 days
*/
/*
~write program to convert decimal to binary
~write a program to pront a table of any given number
~write a program to find largest number of three number
~write a program to swap two number without using third variable
~write a program to convert temp farnhite to celcius
~write a program to display minimum value ,max value and size of all primitive
 datatype
 ~display default value of instance variable of primitive datatype.
  also write your comment in error message generated by omplier if
  -1.if instance variable(non static) are trying to access in main method;
  -2.local variable are used without initalize.
  /* write a class circle and declare appropiate instance variable constructor
  and method which accept and store radius from the user and compute area of the
  circle
  write a class codelateral whcih has appropiae instance variable constructors
  and overloaded area method to compute area of rectangle and are of sphere.
  
